# task
task_index: 5
#is_fliped: false

# path
path_design: "../data/design/design.txt"
path_topo: "../data/design/design_seg.txt"
path_m: "../data/detection/fake_result_m_%d_%d.txt"
path_b: "../data/detection/fake_result_b_%d_%d.txt"
path_t: "../data/design/design_targets.txt"
path_result_pre: "../data/adaptation/result_pre_%d.txt"
path_result: "../data/adaptation/result_%d.txt"
path_result_target: "../data/adaptation/result_target_%d.txt"

# constraint:
distance: 0.01  # in meter
angle_l: 20.0  # in degree
angle_u: 160.0  # in degree

# optimization
mu: 2.0
