# marker
path_img: "../data_2D/"
path_result: "../../data/localization_and_mapping/"
save_init_index: 30
num_photos: 30
num_markers: 7
marker_size: 0.07681882  # size in meter
reorder: true
reorder_indices_list: [0, 1, 2, 3, 4, 5, 7]

# corner_refinement
# CORNER_REFINE_NONE: 0
# CORNER_REFINE_SUBPIX: 1
# CORNER_REFINE_CONTOUR: 2
# CORNER_REFINE_APRILTAG: 3
corner_refinement: 3

# optimization
view_corner: false
