# task definition
task_index: 5
num_poles: 37

# path
path_topo: "../../../data/design/design_seg.txt"
path_w2k: "../../../data/localization_and_mapping/w2k.txt"
path_det_result: "../../../data/detection/result_b_%d_-1.txt"  # detection result
path_adt_result: "../../../data/adaptation/result_%d.txt"  # adaptation result

# marker
num_photos: 9
num_markers: 7
marker_size: 0.07681882  # size in meter
reorder: true
reorder_indices_list: [0, 1, 2, 3, 4, 5, 7]

# corner_refinement
# CORNER_REFINE_NONE: 0
# CORNER_REFINE_SUBPIX: 1
# CORNER_REFINE_CONTOUR: 2
# CORNER_REFINE_APRILTAG: 3
corner_refinement: 3
