# task type
# SCAN_MATERIAL 0
# SCAN_BUILT 1
task_type: 1
task_index: 4
num_poles: 37

# task node type
# NODE_FROM 0
# NODE_TO 1
task_node_type: 0

# path
path_img: "../../data2D/"
path_design: "../../../data/design/design.txt"
path_design_m: "../../../data/design/design_m.txt"  # for scanning the material
path_topo: "../../../data/design/design_seg.txt"
path_w2k: "../../../data/localization_and_mapping/built/w2k.txt"
path_cloud: "../../data3D/"
path_result: "../../../data/detection/"

# marker
num_angles: 5
num_photos_per_angle: 5

# num_markers: 13
num_markers: 27
marker_size: 0.07681882  # size in meter
reorder: true
# reorder_indices_list: [48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36]
reorder_indices_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20]

# corner_refinement
# CORNER_REFINE_NONE: 0
# CORNER_REFINE_SUBPIX: 1
# CORNER_REFINE_CONTOUR: 2
# CORNER_REFINE_APRILTAG: 3
corner_refinement: 3
view_corner: false

# segmentation
# seg_length: 0.04  # size in meter
seg_length: 0.04
# depth value larger than "dis_max" will be ignored
dis_max: 2.0  # size in meter
# distance from 3d point to design axis larger than "seg_thresh" are outliers
seg_thresh: 0.03  # size in meter

# cloud processing
leaf_size: 0.0015  # size in meter
mean_k: 8  # for statistical outlier removal
# pass_through_height: 0.058
pass_through_height: 0.005
ransac_thresh: 0.06

# cylinder fitting
radius: 0.00984  # size in meter
fit_thresh: 0.1  # size in meter
